"""Adicao models

Revision ID: 0cb2d5003c61
Revises: 
Create Date: 2021-05-13 09:07:26.741290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cb2d5003c61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_dominio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tp_dominio', sa.String(), nullable=True),
    sa.Column('nm_dominio', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nm_usuario', sa.String(), nullable=True),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('senha', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('nm_usuario')
    )
    op.create_table('tb_animal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_tp_animal', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('fl_buscando_parceiro', sa.Boolean(), nullable=True),
    sa.Column('fl_para_adocao', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_tp_animal'], ['tb_dominio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_autenticacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['tb_usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_animal', sa.Integer(), nullable=True),
    sa.Column('id_animal_para', sa.Integer(), nullable=True),
    sa.Column('mensagem', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_animal'], ['tb_animal.id'], ),
    sa.ForeignKeyConstraint(['id_animal_para'], ['tb_animal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_denuncia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_animal', sa.Integer(), nullable=True),
    sa.Column('motivo', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_animal'], ['tb_animal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_relacao_match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_animal', sa.Integer(), nullable=True),
    sa.Column('id_animal_match', sa.Integer(), nullable=True),
    sa.Column('fl_match', sa.Boolean(), nullable=True),
    sa.Column('fl_match_animal_match', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_animal'], ['tb_animal.id'], ),
    sa.ForeignKeyConstraint(['id_animal_match'], ['tb_animal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_usuario_animal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_animal', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_animal'], ['tb_animal.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['tb_usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_usuario_animal')
    op.drop_table('tb_relacao_match')
    op.drop_table('tb_denuncia')
    op.drop_table('tb_chat')
    op.drop_table('tb_autenticacao')
    op.drop_table('tb_animal')
    op.drop_table('tb_usuario')
    op.drop_table('tb_dominio')
    # ### end Alembic commands ###
