swagger: "2.0"
info:
  description: "Projeto para entrevista do CONTA SIMPLES"
  version: "1.0.0"
  title: "Swagger Projeto - Conta Simples"
  contact:
    email: "gustavo.honoratonic@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "127.0.0.1:8080"
basePath: "/v1"
tags:
  - name: "Usuário"
    description: "API de Usuários"
  - name: "Autenticação"
    description: "API para validação de usuários"
schemes:
  - "https"
  - "http"
paths:

  /usuario:
    post:
      tags:
        - "Usuário"
      operationId: "post_usuario"
      summary: "Cadastro de usuário"
      description: "Faz o cadastro de um usuário"
      consumes:
        - application/json
      parameters:
        - name: "body"
          in: "body"
          required: true
          description: "Corpo da requisição"
          schema:
            $ref: "#/definitions/UsuarioVO"
      responses:
        201:
          description: "Usuário criado com sucesso"
          schema:
            $ref: "#/definitions/Usuario"
        500:
          description: "Erro no servidor"
      x-swagger-router-controller: "server.controllers.usuario_controller"
  /usuario/{id_usuario}/animal:
    get:
      tags:
        - "Usuário"
      operationId: "get_usuario_animal"
      summary: "Cadastro de usuário"
      description: "Faz o cadastro de um usuário"
      consumes:
        - application/json
      parameters:
        - name: "id_usuario"
          in: path
          required: true
          type: "integer"
          description: "Id do usuário"
      responses:
        200:
          description: "Usuário retornado com sucesso"
          schema:
            $ref: "#/definitions/Usuario"
        500:
          description: "Erro no servidor"
      x-swagger-router-controller: "server.controllers.usuario_controller"
  /dominios:
    get:
      tags:
        - "dominio"
      operationId: "get_listar_dominios"
      summary: "Lista dominios"
      description: "Lista dominios"
      produces:
        - "application/json"
      parameters:
        - name: "tp_dominio"
          in: "query"
          required: false
          description: "Busca os dominios por um tipo de dominio"
          type: "string"
        - name: "nm_dominio"
          in: "query"
          required: false
          type: "string"
          description: "Busca os dominios por um nome de dominio"
      responses:
        200:
          description: "Retorna uma lista com todos os dominios"
          schema:
            $ref: "#/definitions/DominioPaginado"
        500:
          description: "Erro que o servidor não soube lidar"
      x-swagger-router-controller: "server.controllers.dominio_controller"
  /autenticacao:
    post:
      tags:
        - "Autenticação"
      operationId: "post_autenticacao"
      summary: "Faz a autenticacao de um usuario"
      description: "Faz a autenticacao de um usuario"
      consumes:
        - application/json
      parameters:
        - name: "body"
          in: "body"
          required: true
          description: "Corpo da requisição"
          schema:
            $ref: "#/definitions/AutenticacaoVO"
      responses:
        200:
          description: "Autenticado com sucesso!"
          schema:
            $ref: "#/definitions/Autenticacao"
        500:
          description: "Erro no servidor"
      x-swagger-router-controller: "server.controllers.login_controller"
  /match:
    post:
      tags:
        - "Match"
      operationId: "post_match"
      summary: "Cria o match"
      description: "Match"
      consumes:
        - application/json
      parameters:
        - name: "body"
          in: "body"
          required: true
          description: "Corpo da requisição"
          schema:
            $ref: "#/definitions/MatchVO"
      responses:
        200:
          description: "Autenticado com sucesso!"
          schema:
            $ref: "#/definitions/MatchVO"
        500:
          description: "Erro no servidor"
      x-swagger-router-controller: "server.controllers.match_controller"
  /animal:
    post:
      tags:
        - "Animal"
      operationId: "post_animal"
      summary: "Cria o Animal"
      description: "Animal"
      consumes:
        - application/json
      parameters:
        - name: "body"
          in: "body"
          required: true
          description: "Corpo da requisição"
          schema:
            $ref: "#/definitions/AnimalVO"
      responses:
        200:
          description: "Autenticado com sucesso!"
          schema:
            $ref: "#/definitions/AnimalVO"
        500:
          description: "Erro no servidor"
      x-swagger-router-controller: "server.controllers.animal_controller"

definitions:
  Paginado:
    type: object
    properties:
      page:
        type: integer
        example: 2
      has_next:
        type: boolean
        example: false
      has_prev:
        type: boolean
        example: true
      next_num:
        type: integer
        example: 3
      pages:
        type: integer
        example: 100
      per_page:
        type: integer
        example: 50
      prev_num:
        type: integer
        example: 2
      total:
        type: integer
        example: 5000
  UsuarioVO:
    type: "object"
    properties:
      nome:
        type: "string"
        example: "teste"
      sobrenome:
        type: "string"
        example: "teste"
      email:
        type: "string"
        example: "email"
      senha:
        type: "string"
        example: "senha"

  Usuario:
    type: "object"
    properties:
      id:
        type: "integer"
        example: 1
      created_at:
        type: "string"
        format: "date-time"
      nm_usuario:
        type: "string"
      cpf:
        type: "string"
  UsuarioRelacao:
    type: "object"
    properties:
      id:
        type: "integer"
        example: 1
      nm_usuario:
        type: "string"
  AutenticacaoVO:
    type: "object"
    properties:
      id:
        type: "integer"
        example: 1
      created_at:
        type: "string"
        format: "date-time"
      email:
        type: "string"
  Autenticacao:
    type: "object"
    properties:
      token:
        type: "string"
      expiration_date:
        type: "string"
        format: "date-time"
      created_at:
        type: "string"
        format: "date-time"
      relacao_usuario:
        $ref: '#/definitions/UsuarioRelacao'
  MatchVO:
    type: "object"
    properties:
      id_animal:
        type: "integer"
      id_animal_match:
        type: "integer"
      fl_match:
        type: "boolean"
      fl_match_animal_match:
        type: "boolean"
  AnimalVO:
    type: "object"
    properties:
      id_usuario:
        type: "integer"
      id_tp_animal:
        type: "integer"
      nome:
        type: "string"
      descricao:
        type: "string"
      fl_buscando_parceiro:
        type: "boolean"
      fl_para_adocao:
        type: "boolean"
  DominioPaginado:
    allOf:
      - $ref: '#/definitions/Paginado'
      - type: object
        properties:
          items:
            type: array
            items:
              $ref: '#/definitions/Dominio'
  Dominio:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      tp_dominio:
        type: "string"
        x-nullable: true
      nm_dominio:
        type: "string"
        x-nullable: true

